# Generated by Django 5.2.8 on 2025-11-11 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteSubestacion',
            fields=[
                ('id_componente_sube', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_componente', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('circuito', 'Circuito'), ('transformador', 'Transformador'), ('servicios', 'Servicios Auxiliares')], default='circuito', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id_comunicacion', models.AutoField(primary_key=True, serialize=False)),
                ('modem', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('ip_vieja', models.GenericIPAddressField(blank=True, null=True)),
                ('asdu', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('tecnologia', models.CharField(max_length=100)),
                ('estado_actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_modem', models.CharField(max_length=100)),
                ('activo_modem', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='formu_sube_circuito',
            fields=[
                ('id_formu_sube_circuito', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InformeReco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_actividad', models.DateTimeField()),
                ('falla_identificada', models.TextField()),
                ('causa_falla', models.TextField()),
                ('trabajo_realizado', models.TextField()),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('id_fotos', models.CharField(blank=True, max_length=255, null=True)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('aviso_telco', models.BooleanField(default=False)),
                ('aviso_mante', models.BooleanField(default=False)),
                ('detalle_telco', models.TextField(blank=True, null=True)),
                ('detalle_mante', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id_nodo', models.AutoField(primary_key=True, serialize=False)),
                ('nodo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('circuito1', models.CharField(blank=True, max_length=100, null=True)),
                ('circuito2', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nt', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenSubestacion',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden_sube', models.CharField(max_length=50, unique=True)),
                ('descripcion_orden_sube', models.TextField()),
                ('estado_orden', models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_por_revisar', 'pendiente por revisar'), ('completada', 'Completada')], default='pendiente', max_length=30)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('bahia/interruptor', 'Inspecciones Bahía'), ('transformador', 'Inspección Transformador'), ('servicios', 'Servicios Auxiliares'), ('observaciones', 'Observaciones Generales')], default='bahia', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioIngeniero',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_comunicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.comunicacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoReco',
            fields=[
                ('id_histo', models.AutoField(primary_key=True, serialize=False)),
                ('id_comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.comentarioingeniero')),
                ('informes', models.ManyToManyField(related_name='historicos', to='mantenimiento.informereco')),
            ],
        ),
        migrations.CreateModel(
            name='FotoInformeReco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='informes_reco/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mantenimiento.informereco')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_orden', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('subestacion', 'Subestación'), ('reco', 'Reconectador')], max_length=20)),
                ('estado_orden', models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_por_revisar', 'Pendiente por revisar'), ('completada', 'Completada')], max_length=30)),
                ('id_nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.nodo')),
                ('id_subestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.subestacion')),
            ],
        ),
        migrations.AddField(
            model_name='informereco',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_reco', to='mantenimiento.orden'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('texto', 'Texto libre'), ('opcion', 'Bien/Mal')], default='texto', max_length=20)),
                ('categoria', models.CharField(choices=[('bahia', 'Inspecciones Bahía'), ('transformador', 'Inspección Transformador'), ('servicios', 'Servicios Auxiliares'), ('observaciones', 'Observaciones Generales')], default='bahia', max_length=30)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subpreguntas', to='mantenimiento.preguntapadre')),
            ],
        ),
        migrations.CreateModel(
            name='Reconectador',
            fields=[
                ('id_reco', models.AutoField(primary_key=True, serialize=False)),
                ('activo_reco', models.IntegerField(blank=True, default=0, null=True)),
                ('sn_activo', models.CharField(blank=True, max_length=100, null=True)),
                ('n_equipo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reconectadores_fotos/')),
                ('serial_reco', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('estado_bateria', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_bateria', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_reconectador', models.CharField(blank=True, max_length=100, null=True)),
                ('Icc', models.CharField(blank=True, max_length=100, null=True)),
                ('id_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.nodo')),
            ],
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='id_reco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.reconectador'),
        ),
        migrations.CreateModel(
            name='RevisionSubestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='mantenimiento.ordensubestacion')),
                ('subestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.subestacion')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=200, null=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='mantenimiento.componentesubestacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.pregunta')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.revisionsubestacion')),
            ],
        ),
        migrations.AddField(
            model_name='ordensubestacion',
            name='id_subestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_subestacion', to='mantenimiento.subestacion'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='id_subestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.subestacion'),
        ),
        migrations.CreateModel(
            name='HistoricoSubestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.ordensubestacion')),
                ('subestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='mantenimiento.subestacion')),
            ],
        ),
        migrations.AddField(
            model_name='componentesubestacion',
            name='subestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='mantenimiento.subestacion'),
        ),
        migrations.CreateModel(
            name='Subestacion_comu_informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('trabajo_realizado_sub_comu', models.TextField()),
                ('otras_observaciones', models.TextField(blank=True, null=True)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('longitud_sub', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('latitud_sub', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Historicosubcomu',
            fields=[
                ('id_historico_sub_comu', models.AutoField(primary_key=True, serialize=False)),
                ('informe_sub_comu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.subestacion_comu_informe')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cc', models.CharField(max_length=20, unique=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.rol')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='asignada_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='mantenimiento.trabajador'),
        ),
        migrations.AddField(
            model_name='orden',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to='mantenimiento.trabajador'),
        ),
    ]
